## Notebook Purpose
This notebook is used to pull out statistics for glacier description in the study site table (Table 1).  

#### Last updated: May 23, 2023

## TODO:
- Update imports when new library has been built up with all updates
-Generalise path to data products during revisions, after the data distribution plan is finalized


In [1]:
%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format='retina'
%matplotlib inline

In [3]:
import numpy as np 
import geopandas as gpd
import matplotlib.pyplot as plt
from imview import pltlib
import pandas as pd
from pygeotools.lib import warplib,geolib,iolib,malib,filtlib,timelib
import os,sys,glob,shutil
from velocity_proc import glac_dyn, constants, velocity_filter, velocity_timeseries

/swbuild/sbhusha1/miniconda3/envs/bhushanGDAL3/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Ngozumpa

In [4]:
glac_name = 'ngozumpa'
shp = gpd.read_file(constants.fetch_glac_shp(constants.rgi_dicts[glac_name])).to_crs('EPSG:32645')
glac_thick_ds = iolib.fn_getds(constants.fetch_farinotti_thickness(glac_name))
res = geolib.get_res(glac_thick_ds)[0]
glac_thick = iolib.ds_getma(glac_thick_ds)
deb_thick_ds = iolib.fn_getds(constants.fetch_rounce_debris_thickness(glac_name))
res_deb = geolib.get_res(deb_thick_ds)[0]
deb_thick = iolib.ds_getma(deb_thick_ds)

In [5]:
shp.area/(glac_thick.count()*res*res)

0    0.999331
dtype: float64

In [6]:
glac_thick.count()*res*res*1e-6

61.0475

In [7]:
deb_thick.count()*res_deb*res_deb*1e-6

19.088549999999998

In [8]:
((deb_thick.count()*res_deb*res_deb)/shp.area)*100

0    31.289294
dtype: float64

In [9]:
np.nanpercentile(deb_thick.compressed(),(5,16,50,84,95))

array([0.02812129, 0.13449664, 0.47741808, 1.78103662, 3.        ])

# Khumbu

In [10]:
glac_name = 'khumbu'
shp = gpd.read_file(constants.fetch_glac_shp(constants.rgi_dicts[glac_name])).to_crs('EPSG:32645')
glac_thick_ds = iolib.fn_getds(constants.fetch_farinotti_thickness(glac_name))
res = geolib.get_res(glac_thick_ds)[0]
glac_thick = iolib.ds_getma(glac_thick_ds)
deb_thick_ds = iolib.fn_getds(constants.fetch_rounce_debris_thickness(glac_name))
res_deb = geolib.get_res(deb_thick_ds)[0]
deb_thick = iolib.ds_getma(deb_thick_ds)

In [11]:
glac_thick.count()*res*res*1e-6

19.0825

In [12]:
shp.area*1e-6

0    19.081582
dtype: float64

In [13]:
deb_thick.count()*res_deb*res_deb*1e-6

7.352694

In [14]:
((deb_thick.count()*res_deb*res_deb)/shp.area)*100

0    38.532937
dtype: float64

In [15]:
np.nanpercentile(deb_thick.compressed(),(5,16,50,84,95))

array([0.0162879 , 0.06124099, 0.29475071, 1.7283973 , 3.        ])

# Imja

In [16]:
glac_name = 'imja'
shp = gpd.read_file(constants.fetch_glac_shp(constants.rgi_dicts[glac_name])).to_crs('EPSG:32645')
glac_thick_ds = iolib.fn_getds(constants.fetch_farinotti_thickness(glac_name))
res = geolib.get_res(glac_thick_ds)[0]
glac_thick = iolib.ds_getma(glac_thick_ds)
deb_thick_ds = iolib.fn_getds(constants.fetch_rounce_debris_thickness(glac_name))
res_deb = geolib.get_res(deb_thick_ds)[0]
deb_thick = iolib.ds_getma(deb_thick_ds)

In [17]:
shp.area*1e-6

0    14.254544
dtype: float64

In [18]:
glac_thick.count()*res*res*1e-6

14.259374999999999

In [19]:
((deb_thick.count()*res_deb*res_deb)/shp.area)*100

0    40.749617
dtype: float64

In [20]:
np.nanpercentile(deb_thick.compressed(),(5,16,50,84,95))

array([0.0326701 , 0.09261377, 0.31181386, 0.53447376, 0.83649198])

# Langtang

In [21]:
glac_name = 'langtang'
shp = gpd.read_file(constants.fetch_glac_shp(constants.rgi_dicts[glac_name])).to_crs('EPSG:32645')
glac_thick_ds = iolib.fn_getds(constants.fetch_farinotti_thickness(glac_name))
res = geolib.get_res(glac_thick_ds)[0]
glac_thick = iolib.ds_getma(glac_thick_ds)
deb_thick_ds = iolib.fn_getds(constants.fetch_rounce_debris_thickness(glac_name))
res_deb = geolib.get_res(deb_thick_ds)[0]
deb_thick = iolib.ds_getma(deb_thick_ds)

In [22]:
shp.area*1e-6

0    37.776506
dtype: float64

In [23]:
((deb_thick.count()*res_deb*res_deb)/shp.area)*100

0    44.748876
dtype: float64

In [24]:
np.nanpercentile(deb_thick.compressed(),(5,16,50,84,95))

array([0.04004339, 0.20279822, 0.67204264, 1.49267059, 3.        ])

# Lirung

In [25]:
glac_name = 'lirung'
shp = gpd.read_file(constants.fetch_glac_shp(constants.rgi_dicts[glac_name])).to_crs('EPSG:32645')
glac_thick_ds = iolib.fn_getds(constants.fetch_farinotti_thickness(glac_name))
res = geolib.get_res(glac_thick_ds)[0]
glac_thick = iolib.ds_getma(glac_thick_ds)
deb_thick_ds = iolib.fn_getds(constants.fetch_rounce_debris_thickness(glac_name))
res_deb = geolib.get_res(deb_thick_ds)[0]
deb_thick = iolib.ds_getma(deb_thick_ds)

debris thickness not found, will return extrap product


In [26]:
shp.area*1e-6

0    1.459637
dtype: float64

In [27]:
deb_thick.count()*res_deb*res_deb*1e-6

1.415232

In [28]:
((deb_thick.count()*res_deb*res_deb)/(glac_thick.count()*res*res))*100

97.09996569468268

In [29]:
np.nanpercentile(deb_thick.compressed(),(5,16,50,84,95))

array([0.15286841, 0.21394299, 0.3619173 , 0.53262957, 0.6263999 ])

# Changri Nup (Black Changri Nup)

In [30]:
glac_name = 'changri_nup'
shp = gpd.read_file(constants.fetch_glac_shp(constants.rgi_dicts[glac_name])).to_crs('EPSG:32645')
glac_thick_ds = iolib.fn_getds(constants.fetch_farinotti_thickness(glac_name))
res = geolib.get_res(glac_thick_ds)[0]
glac_thick = iolib.ds_getma(glac_thick_ds)
deb_thick_ds = iolib.fn_getds(constants.fetch_rounce_debris_thickness(glac_name))
res_deb = geolib.get_res(deb_thick_ds)[0]
deb_thick = iolib.ds_getma(deb_thick_ds)

In [31]:
ds_list = warplib.memwarp_multi([glac_thick_ds,deb_thick_ds])
res,res_deb = geolib.get_res(ds_list[0])
glac_thick,deb_thick = [iolib.ds_getma(ds) for ds in ds_list]



Warping all inputs to the following:
Resolution: 25.0
Extent: [476612.5, 3094162.5, 482987.5, 3099437.5]
Projection: '+proj=utm +zone=45 +datum=WGS84 +units=m +no_defs'
Resampling alg: cubic

1 of 2: /nobackup/sbhusha1/hma/ngozumpa_lagdz/icethickness/RGI60-15/RGI60-15.03734_thickness.tif
2 of 2: /nobackupp11/sbhusha1/hma/lagdz_samples/debris_thickness/HMA_DTE_15.03734_hdts_m.tif
nl: 211 ns: 255 res: 25.000
0...10...20...30...40...50...60...70...80...90...

In [32]:
glac_shp = gpd.read_file('/nobackup/sbhusha1/hma/agu22_scratch/Black_changri_with_accumulation_area2.shp')
glac_thick_ma = velocity_timeseries.mask_by_shp(glac_shp.geometry,glac_thick,ds_list[0])
deb_thick_ma = velocity_timeseries.mask_by_shp(glac_shp.geometry,deb_thick,ds_list[1])

In [33]:
deb_thick_ma.count()*res_deb*res_deb*1e-6

1.26125

In [34]:
res_deb

25.0

In [35]:
res

25.0

In [36]:
((deb_thick_ma.count()*res_deb*res_deb)/(glac_thick_ma.count()*res*res))*100

53.358011634056055

In [37]:
np.nanpercentile(deb_thick.compressed(),(5,16,50,84,95))

array([0.09340205, 0.29517524, 0.92171839, 3.        , 3.        ])

In [38]:
malib.get_stats_dict(deb_thick.compressed())

{'count': 11724,
 'min': 0.0032886057160794735,
 'max': 3.1680309772491455,
 'ptp': 3.1647424697875977,
 'mean': 1.343993825297558,
 'std': 1.081438807939735,
 'nmad': 0.9556243604063988,
 'med': 0.9217183887958527,
 'median': 0.9217183887958527,
 'p16': 0.295175244808197,
 'p84': 3.0,
 'spread': 1.3524123775959014,
 'mode': 3.0}